export const GET_DOGS_PICTURES_REQUEST_ACTION =
  "DOGS::GET_DOGS_PICTURES_REQUEST_ACTION";

export const GET_DOGS_PICTURES_SUCCESS_ACTION =
  "DOGS::GET_DOGS_PICTURES_SUCCESS_ACTION";

export const GET_DOGS_PICTURES_REFUSE_ACTION =
  "DOGS::GET_DOGS_PICTURES_REFUSE_ACTION";

export const GET_DOGS_PICTURES_COMPLETE_ACTION =
  "DOGS::GET_DOGS_PICTURES_COMPLETE_ACTION";
